# require: rubocop-rspec

# Пример отключения конкретной проверки в файле:
# rubocop:disable MethodLength
#
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'config/initializers/simple_form*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - Guardfile

# Offense count: 11
Metrics/AbcSize:
  Max: 45

# Offense count: 2
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 305
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 708

# Offense count: 23
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 230

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 2
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 1
#Performance/TimesMap:
  #Exclude:
    #- 'app/models/example_visits.rb'

# Offense count: 44
Style/AsciiComments:
  Enabled: false

# Offense count: 5
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/helpers/account/clients_helper.rb'
    - 'app/helpers/account/segments_helper.rb'
    - 'app/helpers/account/settings_helper.rb'
    - 'app/helpers/account/variants_helper.rb'
    - 'app/helpers/account/welcome_helper.rb'


# Offense count: 226
Style/Documentation:
  Enabled: false

# Offense count: 2
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'config/unicorn.rb'
