apps:
  -
    title: BML
    asset_host: <%= ENV['ASSET_HOST'] || 'http://bmland.dev' %>
    from: 'from@<%= ENV['HOST'] %>'
    tld_length: <%= ENV['TLD'] %>
    domain_zones:
      - aydamaster.ru
      - bmland.ru
      - <%= ENV['HOST'] || 'bmland.dev' %>

    default_url_options: 
      host: <%= ENV['HOST'] || 'bmland.dev' %>
      port: <%= ENV['PORT'] || 3000 %>
