defaults: &defaults
  tld_length: 1

  domain_zones:
    - 3008.vkontraste.ru
    - aydamaster.ru
    - bmland.ru

  exclusion_landing_paths:
    - /assets
    - /images
    - /robots.txt
    - /api
    - /admin
    - /fonts

  reserved_subdomains:
    - www
    - app
    - api
    - admin

  app: &app
    title: "[bm]land"
    asset_host: http://3008.vkontraste.ru
    host: http://3008.vkontraste.ru

    default_domain: bmland.ru

    default_url_options: &default_url_options
      host: 3008.vkontraste.ru
      port: 80

  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      <<: *default_url_options
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 25


  mailer_defaults: &mailer_defaults
    from: 'noreply@aydamaster.ru'
    host: aydamaster.ru

development:
  <<: *defaults
  domain_zones:
    - aydamaster.ru
    - bmland.ru
    - <%= ENV['HOST'] || 'bmland.dev' %>

  app:
    <<: *app
    asset_host: <%= ENV['ASSET_HOST'] || 'http://bmland.dev' %>

    default_domain: <%= ENV['HOST'] %>
    default_url_options: &default_url_options
      host: <%= ENV['HOST'] || 'bmland.dev' %>
      port: <%= ENV['PORT'] || 3000 %>

  tld_length: <%= ENV['TLD'] || 2 %>
  action_mailer:
    <<: *action_mailer
    delivery_method: :letter_opener
    # mailcatcher
    #delivery_method: :smtp
    #smtp_settings:
      #address: localhost
      #port: 1025   # mailcatcher
    raise_delivery_errors: true

production:
  <<: *defaults
  domain_zones:
    - aydamaster.ru
    - bmland.ru

  fallback_image: /images/fallback/product-none.png
  app:
    <<: *app
    title: bmland.ru

    default_domain: aydamaster.ru
    asset_host: http://aydamaster.ru

    default_url_options: &default_url_options
      host: aydamaster.ru
      port: 80

  tld_length: 1
  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      host: aydamaster.ru
      port: 80
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 25
  mailer_defaults:
    from: 'noreply@aydamaster.ru'
    host: aydamaster.ru

test:
  <<: *defaults
  domain_zones:
    - example.com
    - aydamaster.ru
    - bmland.ru

  app:
    # title: "[bm]land"
    title: Ай-да Мастер!

    asset_host: http://example.com
    fallback_image: images/fallback/product-none.png
    default_domain: example.com

    default_url_options: &default_url_options
      host: example.com
      port: 3000

    host: http://app.example.com:3000

  capybara:
    port: 57500

  mailer_defaults:
    <<: *mailer_defaults

  action_mailer:
    <<: *action_mailer
    delivery_method: :test
