tld_length: <%= ENV['TLD'] || 1 %>
fallback_image: /images/fallback/product-none.png
maximal_money: 100_000_000
maximal_per_page: 100
exclusion_landing_paths:
  - /assets
  - /dist
  - /favicon.ico
  - /favicons
  - /images
  - /robots.txt
  - /sitemap.xml
  - /api
  - /admin
  - /fonts

reserved_subdomains:
  - www
  - app
  - api
  - admin
  - super
  - root
  - assets
  - images

admin_ids:
  - 1 # danil
