tld_length: <%= ENV['TLD'] || 1 %>
fallback_image: /images/fallback/product-none.png
maximal_money: 100_000_000
exclusion_landing_paths:
  - /assets
  - /images
  - /robots.txt
  - /api
  - /admin
  - /fonts

reserved_subdomains:
  - www
  - app
  - api
  - admin
  - super
  - root
  - assets
  - images

admin_ids:
  - 1 # danil
